
services:
  tenzak-db:
    image: mysql:8.0
    container_name: tenzak-db-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: tenzak_db
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - tenzak-db:/var/lib/mysql

volumes:
  tenzak-db:
